version: "3"

services:
  frontend:
    build:
      context: ./frontend/
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/app:/app
    command: >
      sh -c "npm run serve"
    depends_on:
      - app
  app:
    build:
      context: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=secretPassword
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretPassword
