# Generated by Django 3.2.2 on 2021-05-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_subarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.area')),
                ('document_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.document')),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.subarea')),
            ],
        ),
    ]
