# Generated by Django 3.2.2 on 2021-05-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='document',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
