# Generated by Django 3.2.2 on 2021-05-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.document'),
        ),
    ]
